version: 2.1

orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@2.0.3
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      # Install all dependencies [frontend]
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # Install all dependencies [backend]
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      # Build application [frontend]
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Build application [backend]
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      # Run tests [frontend]
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      # Run tests [backend]
      - run:
          name: Back-End Test
          command: |
            npm run backend:test 
      # Deploy build folder to S3 [frontend]
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy 
      # Deploy build folder to Elastic Beanstalk [backend]
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy 

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
